Improvements for the `DiffCalculation` plugin
aiidateam/aiida-diff pull request #20
Opened 2019-05-13 17:39 UTC by sphuber

Removes duplicated input port definitions and gets rid of class
variables used to set the defaults for metadata inputs. Since these are
set on the process spec, they should be retrieved from the process spec
or the actual inputs, depending on the use case. For example in the
`prepare_for_submission` the actual values passed to the process should
be used, otherwise making them configurable options does not make sense
if we are always going to override them with the class variable.

2019-05-13 18:01 UTC, ltalirz commented on aiida_diff/calculations.py
> +        codeinfo.stdout_name = self.metadata.output_filename
```suggestion
        codeinfo.stdout_name = self.metadata.options.output_filename
```

2019-05-13 18:05 UTC, ltalirz requested changes
Thanks, just a minor issue.
Also, pre-commit is failing - are you perhaps using a yapf version different from 0.27?

2019-05-16 14:16 UTC, ltalirz commented
@sphuber the tests also fail with the beta3
do you happen to know why?

https://travis-ci.org/aiidateam/aiida-diff/jobs/532370300#L1057

2019-05-16 14:22 UTC, sphuber commented
I think I do, I just pushed what I think should fix it. The problem is that in the parses it is opening a handle to the output file in the retrieved folder in non-binary mode. But the repository manager underneath the `SinglefileData` opens a binary handle to write it to the repo. The solution is to simply open the file in the parser in binary mode. I have had quite a few bugs related to binary and non-binary (as well as encoding) of files and it still needs to be discussed in depth.

2019-05-16 15:03 UTC, sphuber commented
Ok, that fixed the tests. Now only the docs are failing. I will push a fix

2019-05-16 15:03 UTC, ltalirz commented
now just the docs remain: https://travis-ci.org/aiidateam/aiida-diff/jobs/533351328#L961
we fixed this error in aiida-core some time ago, no?

2019-05-16 15:04 UTC, ltalirz commented
One last thing, could you bump the dependency to b3?

2019-05-16 15:13 UTC, sphuber commented
Done and done. Version is updated and tests should pass now

2019-05-16 15:52 UTC, ltalirz approved these changes
-0.2% coverage ,terrible!

thanks a lot ;-)

2019-05-16 15:52 UTC, merged